### ISSUE TITLE
Syntax for asset instructions is invalid in code source

### ISSUE THREAD

**Issue by LaurentOngaro** [GDQuest/godot-demo-projects-remake#10]
I'm submitting a

- [x] Bug report.

## Bug report ##

Syntax for asset instructions is invalid in code source

**What is the current behavior?**
The project can not be executed

**What is the expected behavior?**
The project can be executed

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 
Run the project
An  error occurs at line #77 of Settings.gd file

**Comment by NathanLovato** [comment]
Thanks but I have to archive this repo, it's not meant to be used. The demo remake already got merged in the official demos.
