### ISSUE TITLE
Unused argument warnings

### ISSUE THREAD

**Issue by aaronfranke** [GDQuest/godot-demo-projects-remake#6]
Enemy.gd line 35, Coin.gd line 14, Player.gd line 32. All of these need to have their arguments preceded with underscores to dismiss the unused argument warning. Ex: `_delta`.

**Comment by NathanLovato** [comment]
You suppress all warnings in official demos? To me, they're fine - they're just warnings, not errors. Also, renaming arguments feels like a magic trick to me. How about either disabling this warning in the project, or locally, with the comments notation?

**Comment by NathanLovato** [comment]
I went with the `# warning-ignore:unused_argument` comments for now, tell me if that's not okay.

**Comment by aaronfranke** [comment]
I consider any warning raised to be an issue, a finished project should not have any.

The warning-ignore system is used for every other warning, and it's kinda fine here, though for the unused argument warning in particular, the "magic trick" of `_` is widely used and I have all of the demo projects using it.

**Comment by NathanLovato** [comment]
> the "magic trick" of _ is widely used

I wrote the manual section on the warning system, with vnen, who wrote the system, as the reviewer. I had never seen or heard of this, and as far as I know, it's not documented. Is this something common in another programming language?

I mean, I don't mind using that if you have it everywhere already - it's a minor detail -, but as a developer, seeing this:

```gdscript
func _process(_delta):
```

Does not tell me "ignore the unused argument". That, on the other hand:

```gdscript
# warning-ignore:unused_argument
func _process(delta):
```

Makes sense even if you don't know a thing about warnings.

<hr>

In any case, should I replace the comments with a leading underscore on the arguments? Then, would the project be ready to PR?
