### ISSUE TITLE
A pixel is not a pixel. All art assets are 2x the necessary size.

### ISSUE THREAD

**Issue by golddotasksquestions** [GDQuest/godot-demo-projects-remake#7]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
If I would like to use this demo as a starting point for my own pixelart platformer, I can't, because simply alter or replacing art assets results in all kinds of unexpected behaviour, because every visual pixel in the assets is 4 actual pixels (all art is 2x scaled up)

**What is the expected behavior?**
Expected behavior would be to be able to simply swap the art asset with some other and start poking around in the code changing values here and there, to create a new enemy or slightly different player behavior ... beginner stuff.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Download the and run the project, see something you would like to experiment with,
2. open one of the art assets in your graphics editing software
3. realize the art is not pixel art
4. try to make it pixelart so you can work with it, by scaling it down
5. run the game
6. realize this breaks everything
--------------------------------------------
1. Download the and run the project, see something you would like to experiment with,
2. swap out one of the art assets with an existing one of your own
3. run the game
4. realize this breaks everything

**Comment by NathanLovato** [comment]
This isn't a bug: you can't just replace the assets in a game project and have everything work, unless they're the exact same resolution. Otherwise, you'll always have some work to do to adapt the collision boxes etc. That's true of any game.

**Comment by NathanLovato** [comment]
To clarify my answer, please report a bug for things that are broken in the current game. Otherwise, it's a feature/enhancement request.

**Comment by golddotasksquestions** [comment]
I reported it as (art asset) bug, because I assumed it was a mistake.
If that's not an art asset bug, what's the purpose of having pixel art scaled up times 2?
It does make simple replacing with other pixelart or amending it impossible for beginners. even for experienced users it's a lot of work and no fun at all. None of the scales in the game matches anymore. 

![platformer_demo_pixelsize](https://user-images.githubusercontent.com/47016402/73655416-5135c480-468e-11ea-8ad7-ce8666906563.png)

Fixing that is a lot of work even and you already have to know the engine to do this. Which defeats the purpose of this demo as a learning device for newcomers quite substantially.

If anyone would want to add another action for the robot dude, they would have to use a 2x2 pixel brush. That would less of a problem if graphic software could also be set to snap the brushtip to a 2x2 pixel grid. But they don't. They snap to single pixels. If I were to set the grid to every 2 pixels and set my brush to snap to the grid, the 2x2 pixel is set in the center, bet the top left corner like it is in the art assets of this project. So you work without snap but constantly have to check and correct your brush strokes to make the 2x2 pixels line up again.

![platformer_demo_pixelsize2](https://user-images.githubusercontent.com/47016402/73656770-1bdea600-4691-11ea-897e-074971ec7e9d.png)

It's absurd. It doubles the work you have to do for no reason. It's irritating to a beginner. It's completely unclear why the art assets are like that in the first place. It makes incredibly hard to experiment with and add stuff to the demo. To me that's as clear cut an art bug as possible. If you think only code can have bugs, well then you have been misinformed.

> you can't just replace the assets in a game project and have everything work

Yes you can. It's called modding.
At least halve the professionals I've worked with in the industry got in because they started learning how stuff works by modding existing assets.

Please reopen this issue.

**Comment by NathanLovato** [comment]
As I said:

> please report a bug for things that are broken in the **current** game. Otherwise, it's a feature/enhancement request.

No need for so much text, I understand that you couldn't do what you wanted with the demo and that frustrates you. And I'm sorry it does. It's still not a bug: the game is not in a broken state right now. That is to say, if you run it as-is, it works.

It is instead lacking a feature or enhancement that you want, i.e. the ability to use this demo as a template. The assets have been like that since the first Godot release 6 years ago, so this has never been a game template.

 If somebody wants to take the time to downscale the graphics and update every node, they're welcome to do so. You're also welcome to open an issue on the main repository, where we're going to contribute this update to the demo.

This task is just beyond the scope of our job, that we're doing benevolently by the way.

So, if you want the graphics changed, would you mind opening this issue on the Godot demos repository?

**Comment by golddotasksquestions** [comment]
Yes, I will open an issue there instead.

> The assets have been like that since the first Godot release 6 years ago, so this has never been a game template.

It has been a template as long as I can remember. It's literally the second project you find in the project manager -> Templates when you look for "Platformer". And as soon as the recently updated version is in the Asset Library it will literally be the first thing when anyone clicks on "Templates".
Which is a very common thing for someone who first opens the editor and wants to experiment/learn on an existing simple project will do.

It **is** still a bug: This is not a game, it's a demo. As a demo it does not fulfill it's purpose because it has this issue. So yes it's as clearly a bug as daylight. Fixing the art asset is not a new feature. It's fixing stuff that already exists. Neither does it improve the asset. The asset is in an unuseable state for a demo. 

Btw, if you closed this issue saying "Sorry, but this that's beyond our scope/time/effort, you need to open this issue over there", we would not have this discussion.

**Comment by NathanLovato** [comment]
Again, a bug is something that does not work as intended. This remake of the demo works as we intend it to work: if you do not modify the source code or art assets, you can play it.

I also think that it's confusing that the official demos are registered as templates as none of them is designed to be flexible or extensible. They were just meant to showcase engine features.

Then it's still strange that the pixel art was upscaled. I don't know why the author did that. But you can draw art at the game's resolution too and it'll work. Be it detailed pixel art or low res painterly/vector-based art.
