### ISSUE TITLE
The player falls through the moving platform when the platform goes up

### ISSUE THREAD

**Issue by rubenjavier** [GDQuest/godot-demo-projects-remake#8]
**I'm submitting a...**

- [X] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
When the player is on  the moving platform and the platform goes up, the player fall through

**What is the expected behavior?**
The player should stay on the platform as this moves upwards or downwards

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

Jump in the moving platform when its reachable, wait till it starts going upwards, the player should fall through

The other non-moving oneway platforms dont suffer from this
This used to happen when Godot 3.0 was released but got fixed... maybe some bug crawled back again.

This was on Windows 10 64bits and Godot 3.2 stable

**Comment by NathanLovato** [comment]
Thanks, I'll check it now

**Comment by NathanLovato** [comment]
It seems increasing the safe margin did the trick. I couldn't reproduce the bug with that margin. But please reopen if it still happens after that fix.
