### ISSUE TITLE
The player still falls through vertically moving platforms, with capsule collision shape

### ISSUE THREAD

**Issue by rubenjavier** [GDQuest/godot-demo-projects-remake#9]
**I'm submitting a...**

- [ x] Bug report.
- [ ] Feature request.

## Bug report ##
The player still falls through vertically moving platforms when this platforms go upward, this is actually a bug with capsule shape just like Godot 3.0 and forward, here is the link of the latest report, but there are some priors:
https://github.com/godotengine/godot/issues/28794

I changed the players collision to a box and this stopped happening
The bug has been moved again to Godot 4.0 (it was supposed to be fixed by 3.2), please Nathan talk with the devs and fix it for 3.2... this would leave the OpenGL branch broken forever for all kind of characters in 2D
Thanks in advance.

**What is the current behavior?**
when a character with a Kinematic2D capsule collision shape walks into a Kinematic2D platform going upwards, the character falls through

**What is the expected behavior?**
the character should stay on top of the platform and move along with it, like it happens when the character collision is a box

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.**

**Comment by NathanLovato** [comment]
Ah I see, thanks!

If there's already a bug report there's not much I can do. The fix may break compatibility, which would be why it's been pushed to 4.0. In any case if it doesn't break compatibility, it'll likely be backported to Godot 3.2.x.
